spring:
  rabbitmq:
    port: '5672'
    host: localhost
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        sink-in-0:
          destination: createq
          contentType: application/json
          group: createq
          queue-name-group-only: true
          bind-queue: true
          exchange-durable: true
          exchange-type: topic
          binder: rabbit
      rabbit:
        bindings:
          isink-in-0:
            consumer:
              max-attempts: 3
              autoBindDlq: true
              dlqTtl: 5000
    function:
      definition: sink
server:
  port: '8091'
resource-service:
  url: 'http://localhost:8090/api/v1/resources/'

song-service:
  url: 'http://localhost:8092/api/v1/songs/'
